### ISSUE TITLE
GHC 8.2.1 compilation error: Constructor ‘Stats.GCStats’ does not have the required strict field(s)

### ISSUE THREAD

**Issue by YoEight** [tibbe/ekg-core#20]
Greetings.

I didn't see it on the issue dashboard so here's the error I got when building my library which has `ekg-core` as a dependency. 

```
[9 of 9] Compiling System.Metrics   ( System/Metrics.hs, dist/build/System/Metrics.o )
System/Metrics.hs:449:16: error:
    • Constructor ‘Stats.GCStats’ does not have the required strict field(s): parBalancedBytesCopied
    • In the expression:
        Stats.GCStats
          {bytesAllocated = 0, numGcs = 0, maxBytesUsed = 0,
           numByteUsageSamples = 0, cumulativeBytesUsed = 0, bytesCopied = 0,
           currentBytesUsed = 0, currentBytesSlop = 0, maxBytesSlop = 0,
           peakMegabytesAllocated = 0, mutatorCpuSeconds = 0,
           mutatorWallSeconds = 0, gcCpuSeconds = 0, gcWallSeconds = 0,
           cpuSeconds = 0, wallSeconds = 0, parTotBytesCopied = 0,
           parMaxBytesCopied = 0, mblocksAllocated = 0}
      In an equation for ‘emptyGCStats’:
          emptyGCStats
            = Stats.GCStats
                {bytesAllocated = 0, numGcs = 0, maxBytesUsed = 0,
                 numByteUsageSamples = 0, cumulativeBytesUsed = 0, bytesCopied = 0,
                 currentBytesUsed = 0, currentBytesSlop = 0, maxBytesSlop = 0,
                 peakMegabytesAllocated = 0, mutatorCpuSeconds = 0,
                 mutatorWallSeconds = 0, gcCpuSeconds = 0, gcWallSeconds = 0,
                 cpuSeconds = 0, wallSeconds = 0, parTotBytesCopied = 0,
                 parMaxBytesCopied = 0, mblocksAllocated = 0}
    |
449 | emptyGCStats = Stats.GCStats
    |                ^^^^^^^^^^^^^...
```

Regards

**Comment by 23Skidoo** [comment]
Latest Hackage release should work with GHC 8.2.1.

**Comment by YoEight** [comment]
I did a bad job as I forgot to mention it uses ` 0.1.1.2` which I believe is the last hackage version.

**Comment by YoEight** [comment]
Not a lot of information but you can find the build here => https://travis-ci.org/YoEight/eventstore/jobs/262834338

**Comment by 23Skidoo** [comment]
Ah, you're using GHC HEAD, i.e. the future 8.4.1. Then this is a duplicate of #19.

**Comment by YoEight** [comment]
My bad, indeed it was my GHC HEAD build.
